language: objective-c
osx_image: xcode8.2

install:
  - gem install xcpretty

script:
  - set -o pipefail && xcodebuild -project Bond.xcodeproj -scheme Bond-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.2' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)
